# Generated by Django 4.1.7 on 2023-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_receipt_delete_userdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="receipt_number",
            field=models.CharField(max_length=50),
        ),
    ]
