# Generated by Django 4.1.7 on 2023-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_receipt_receipt_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
    ]
