# Generated by Django 4.1.7 on 2023-08-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing_app", "0002_uploadedimage_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="extracted_text",
            field=models.TextField(blank=True),
        ),
    ]
