# Generated by Django 4.1.7 on 2023-10-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_signup", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="New_User",
        ),
    ]
