# Generated by Django 4.1.7 on 2023-09-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("recipients", models.TextField()),
                ("cc", models.TextField()),
                ("bcc", models.TextField()),
            ],
        ),
    ]
